spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neoris_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: gestor-movimiento-service
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/